/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libkernel */

#ifndef _Included_libkernel
#define _Included_libkernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libkernel
 * Method:    usleep
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_libkernel_usleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     libkernel
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_libkernel_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     libkernel
 * Method:    lseek
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_libkernel_lseek
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     libkernel
 * Method:    write
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_libkernel_write
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     libkernel
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_libkernel_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     libkernel
 * Method:    getpid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libkernel_getpid
  (JNIEnv *, jclass);

/*
 * Class:     libkernel
 * Method:    kqueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libkernel_kqueue
  (JNIEnv *, jclass);

/*
 * Class:     libkernel
 * Method:    kevent
 * Signature: (IJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_libkernel_kevent
  (JNIEnv *, jclass, jint, jlong, jint, jlong, jint, jlong);

/*
 * Class:     libkernel
 * Method:    memset
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_libkernel_memset
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     libkernel
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_libkernel_socket
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     libkernel
 * Method:    getsockopt
 * Signature: (IIIJJ)I
 */
JNIEXPORT jint JNICALL Java_libkernel_getsockopt
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong);

/*
 * Class:     libkernel
 * Method:    setsockopt
 * Signature: (IIIJI)I
 */
JNIEXPORT jint JNICALL Java_libkernel_setsockopt
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
